package com.example.currencyconverter.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.RequiredArgsConstructor;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

@RequiredArgsConstructor
public enum Currency {
    AFGHANISTAN_AFGHANI("Afghanistan-Afghani"),
    ALBANIA_LEK("Albania-Lek"),
    ALGERIA_DINAR("Algeria-Dinar"),
    ANGOLA_KWANZA("Angola-Kwanza"),
    ANTIGUA_BARBUDA_EAST_CARIBBEAN_DOLLAR("Antigua & Barbuda-East Caribbean Dollar"),
    ARGENTINA_PESO("Argentina-Peso"),
    ARMENIA_DRAM("Armenia-Dram"),
    AUSTRALIA_DOLLAR("Australia-Dollar"),
    AUSTRIA_EURO("Austria-Euro"),
    AUSTRIA_SCHILLING("Austria-Schilling"),
    AZERBAIJAN_MANAT("Azerbaijan-Manat"),
    AZERBAIJAN_NEW_MANAT("Azerbaijan-New Manat"),
    AZERBAIJAN_SECOND_MANAT("Azerbaijan-Second Manat"),
    BAHAMAS_DOLLAR("Bahamas-Dollar"),
    BAHRAIN_DINAR("Bahrain-Dinar"),
    BANGLADESH_TAKA("Bangladesh-Taka"),
    BARBADOS_DOLLAR("Barbados-Dollar"),
    BELARUS_NEW_RUBLE("Belarus-New Ruble"),
    BELARUS_RUBLE("Belarus-Ruble"),
    BELGIUM_EURO("Belgium-Euro"),
    BELGIUM_FRANCS("Belgium-Francs"),
    BELIZE_DOLLAR("Belize-Dollar"),
    BENIN_CFA_FRANC("Benin-Cfa Franc"),
    BERMUDA_DOLLAR("Bermuda-Dollar"),
    BOLIVIA_BOLIVIANO("Bolivia-Boliviano"),
    BOSNIA_HERCEGOVINA_MARKA("Bosnia Hercegovina-Marka"),
    BOSNIA_MARKA("Bosnia-Marka"),
    BOTSWANA_PULA("Botswana-Pula"),
    BRAZIL_REAL("Brazil-Real"),
    BRUNEI_DOLLAR("Brunei-Dollar"),
    BULGARIA_LEV("Bulgaria-Lev"),
    BULGARIA_LEV_NEW("Bulgaria-Lev New"),
    BURKINA_FASO_CFA_FRANC("Burkina Faso-Cfa Franc"),
    BURMA_MYANMAR_KYAT("Burma Myanmar-Kyat"),
    BURMA_KYAT("Burma-Kyat"),
    BURUNDI_FRANC("Burundi-Franc"),
    CAMBODIA_KHMER_RIEL("Cambodia (Khmer)-Riel"),
    CAMBODIA_RIEL("Cambodia-Riel"),
    CAMEROON_CFA_FRANC("Cameroon-Cfa Franc"),
    CANADA_DOLLAR("Canada-Dollar"),
    CAPE_VERDE_ESCUDO("Cape Verde-Escudo"),
    CAYMAN_ISLANDS_DOLLAR("Cayman Islands-Dollar"),
    CENTRAL_AFRICAN_REPUBLIC_CFA_FRANC("Central African Republic-Cfa Franc"),
    CHAD_CFA_FRANC("Chad-Cfa Franc"),
    CHILE_PESO("Chile-Peso"),
    CHINA_RENMINBI("China-Renminbi"),
    COLOMBIA_PESO("Colombia-Peso"),
    COMOROS_FRANC("Comoros-Franc"),
    CONGO_CFA_FRANC("Congo-Cfa Franc"),
    COSTA_RICA_COLON("Costa Rica-Colon"),
    COTE_D_IVOIRE_CFA_FRANC("Cote D'Ivoire-Cfa Franc"),
    CROATIA_EURO("Croatia-Euro"),
    CROATIA_KUNA("Croatia-Kuna"),
    CROSS_BORDER_EURO("Cross Border-Euro"),
    CUBA_CHAVITO("Cuba-Chavito"),
    CUBA_PESO("Cuba-Peso"),
    CURACAO_CARIBBEAN_GUILDER("Curacao-Caribbean Guilder"),
    CYPRUS_EURO("Cyprus-Euro"),
    CYPRUS_POUND("Cyprus-Pound"),
    CZECH_REPUBLIC_KORUNA("Czech Republic-Koruna"),
    DEMOCRATIC_REPUBLIC_OF_CONGO_CONGOLESE_FRANC("Democratic Republic Of Congo-Congolese Franc"),
    DEMOCRATIC_REPUBLIC_OF_CONGO_FRANC("Democratic Republic Of Congo-Franc"),
    DENMARK_KRONE("Denmark-Krone"),
    DJIBOUTI_FRANC("Djibouti-Franc"),
    DOMINICAN_REPUBLIC_PESO("Dominican Republic-Peso"),
    ECUADOR_DOLARES("Ecuador-Dolares"),
    ECUADOR_SUCRE("Ecuador-Sucre"),
    EGYPT_POUND("Egypt-Pound"),
    EL_SALVADOR_COLON("El Salvador-Colon"),
    EL_SALVADOR_DOLARES("El Salvador-Dolares"),
    EL_SALVADOR_DOLLAR("El Salvador-Dollar"),
    EQUATORIAL_GUINEA_CFA_FRANC("Equatorial Guinea-Cfa Franc"),
    ERITREA_NAKFA("Eritrea-Nakfa"),
    ERITREA_NAKFA_SALARY_PAYMENT("Eritrea-Nakfa Salary Payment"),
    ESTONIA_EURO("Estonia-Euro"),
    ESTONIA_KROON("Estonia-Kroon"),
    ESWATINI_LILANGENI("Eswatini-Lilangeni"),
    ETHIOPIA_BIRR("Ethiopia-Birr"),
    EURO_ZONE_EURO("Euro Zone-Euro"),
    FIJI_DOLLAR("Fiji-Dollar"),
    FINLAND_EURO("Finland-Euro"),
    FINLAND_MARKKA("Finland-Markka"),
    FRANCE_EURO("France-Euro"),
    FRANCE_FRANC("France-Franc"),
    GABON_CFA_FRANC("Gabon-Cfa Franc"),
    GAMBIA_DALASI("Gambia-Dalasi"),
    GEORGIA_LARI("Georgia-Lari"),
    GERMANY_FRG_EURO("Germany Frg-Euro"),
    GERMANY_EURO("Germany-Euro"),
    GERMANY_MARK("Germany-Mark"),
    GHANA_CEDI("Ghana-Cedi"),
    GHANA_SECOND_CEDI("Ghana-Second Cedi"),
    GREECE_DRACHMA("Greece-Drachma"),
    GREECE_EURO("Greece-Euro"),
    GRENADA_EAST_CARIBBEAN_DOLLAR("Grenada-East Caribbean Dollar"),
    GUATEMALA_QUETZAL("Guatemala-Quetzal"),
    GUINEA_BISSAU_CFA_FRANC("Guinea Bissau-Cfa Franc"),
    GUINEA_FRANC("Guinea-Franc"),
    GUYANA_DOLLAR("Guyana-Dollar"),
    HAITI_GOURDE("Haiti-Gourde"),
    HONDURAS_LEMPIRA("Honduras-Lempira"),
    HONG_KONG_DOLLAR("Hong Kong-Dollar"),
    HUNGARY_FORINT("Hungary-Forint"),
    ICELAND_KRONA("Iceland-Krona"),
    INDIA_RUPEE("India-Rupee"),
    INDONESIA_RUPIAH("Indonesia-Rupiah"),
    IRAN_RIAL("Iran-Rial"),
    IRAQ_DINAR("Iraq-Dinar"),
    IRELAND_EURO("Ireland-Euro"),
    IRELAND_POUND("Ireland-Pound"),
    ISRAEL_SHEKEL("Israel-Shekel"),
    ITALY_EURO("Italy-Euro"),
    ITALY_LIRA("Italy-Lira"),
    JAMAICA_DOLLAR("Jamaica-Dollar"),
    JAPAN_YEN("Japan-Yen"),
    JERUSALEM_SHEKEL("Jerusalem-Shekel"),
    JORDAN_DINAR("Jordan-Dinar"),
    KAZAKHSTAN_TENGE("Kazakhstan-Tenge"),
    KENYA_SHILLING("Kenya-Shilling"),
    KOREA_WON("Korea-Won"),
    KOSOVO_EURO("Kosovo-Euro"),
    KUWAIT_DINAR("Kuwait-Dinar"),
    KYRGYZSTAN_SOM("Kyrgyzstan-Som"),
    LAOS_KIP("Laos-Kip"),
    LATVIA_EURO("Latvia-Euro"),
    LATVIA_LATS("Latvia-Lats"),
    LEBANON_POUND("Lebanon-Pound"),
    LESOTHO_MALOTI("Lesotho-Maloti"),
    LESOTHO_SOUTH_AFRICAN_RAND("Lesotho-South African Rand"),
    LIBERIA_DOLLAR("Liberia-Dollar"),
    LIBERIA_U_S_DOLLAR("Liberia-U.S. Dollar"),
    LIBYA_DINAR("Libya-Dinar"),
    LITHUANIA_EURO("Lithuania-Euro"),
    LITHUANIA_LITA("Lithuania-Lita"),
    LITHUANIA_LITAS("Lithuania-Litas"),
    LUXEMBOURG_EURO("Luxembourg-Euro"),
    LUXEMBOURG_FRANC("Luxembourg-Franc"),
    MACAO_MOP("Macao-Mop"),
    MACEDONIA_FYROM_ARIA("Macedonia Fyrom-Aria"),
    MACEDONIA_FYROM_DENAR("Macedonia Fyrom-Denar"),
    MACEDONIA_FYROM_DENAR_ARIARY_("Macedonia Fyrom-Denar (Ariary)"),
    MADAGASCAR_ARIARY("Madagascar-Ariary"),
    MADAGASCAR_FRANC("Madagascar-Franc"),
    MALAWI_KWACHA("Malawi-Kwacha"),
    MALAYSIA_RINGGIT("Malaysia-Ringgit"),
    MALDIVES_RUFIYAA("Maldives-Rufiyaa"),
    MALI_CFA_FRANC("Mali-Cfa Franc"),
    MALTA_EURO("Malta-Euro"),
    MALTESE_LIRA("Maltese-Lira"),
    MARSHALL_ISLANDS_DOLLAR("Marshall Islands-Dollar"),
    MARSHALL_ISLANDS_U_S_DOLLAR("Marshall Islands-U.S. Dollar"),
    MARTINIQUE_EURO("Martinique-Euro"),
    MARTINIQUE_FRENCH_FRANCS("Martinique-French Francs"),
    MAURITANIA_FIRST_OUGUIYA("Mauritania-First Ouguiya"),
    MAURITANIA_OUGUIYA("Mauritania-Ouguiya"),
    MAURITIUS_RUPEE("Mauritius-Rupee"),
    MEXICO_NEW_PESO("Mexico-New Peso"),
    MEXICO_PESO("Mexico-Peso"),
    MICRONESIA_DOLLAR("Micronesia-Dollar"),
    MICRONESIA_U_S_DOLLAR("Micronesia-U.S. Dollar"),
    MOLDOVA_LEU("Moldova-Leu"),
    MONGOLIA_TUGRIK("Mongolia-Tugrik"),
    MONTENEGRO_EURO("Montenegro-Euro"),
    MOROCCO_DIRHAM("Morocco-Dirham"),
    MOZAMBIQUE_METICAIS("Mozambique-Meticais"),
    MOZAMBIQUE_METICAL("Mozambique-Metical"),
    MYANMAR_KYAT("Myanmar-Kyat"),
    NAMIBIA_DOLLAR("Namibia-Dollar"),
    NEPAL_RUPEE("Nepal-Rupee"),
    NETHERLANDS_ANTILLES_GUILDER("Netherlands Antilles-Guilder"),
    NETHERLANDS_EURO("Netherlands-Euro"),
    NETHERLANDS_GUILDER("Netherlands-Guilder"),
    NEW_ZEALAND_DOLLAR("New Zealand-Dollar"),
    NICARAGUA_CORDOBA("Nicaragua-Cordoba"),
    NIGER_CFA_FRANC("Niger-Cfa Franc"),
    NIGERIA_NAIRA("Nigeria-Naira"),
    NORWAY_KRONE("Norway-Krone"),
    OMAN_RIAL("Oman-Rial"),
    PAKISTAN_RUPEE("Pakistan-Rupee"),
    PALAU_DOLLAR("Palau-Dollar"),
    PANAMA_BALBOA("Panama-Balboa"),
    PANAMA_DOLARES("Panama-Dolares"),
    PAPUA_NEW_GUINEA_KINA("Papua New Guinea-Kina"),
    PARAGUAY_GUARANI("Paraguay-Guarani"),
    PERU_NUEVO_SOL("Peru-Nuevo Sol"),
    PERU_SOL("Peru-Sol"),
    PHILIPPINES_PESO("Philippines-Peso"),
    POLAND_ZLOTY("Poland-Zloty"),
    PORTUGAL_ESCUDO("Portugal-Escudo"),
    PORTUGAL_EURO("Portugal-Euro"),
    QATAR_RIYAL("Qatar-Riyal"),
    REPUBLIC_OF_NORTH_MACEDONIA_DENAR("Republic Of North Macedonia-Denar"),
    REPUBLIC_OF_PALAU_DOLLAR("Republic Of Palau-Dollar"),
    ROMANIA_LEU("Romania-Leu"),
    ROMANIA_NEW_LEU("Romania-New Leu"),
    ROMANIA_THIRD_LEU("Romania-Third Leu"),
    RUSSIA_RUBLE("Russia-Ruble"),
    RWANDA_FRANC("Rwanda-Franc"),
    SAO_TOME_PRINCIPE_DOBRAS("Sao Tome & Principe-Dobras"),
    SAO_TOME_PRINCIPE_NEW_DOBRAS("Sao Tome & Principe-New Dobras"),
    SAUDI_ARABIA_RIYAL("Saudi Arabia-Riyal"),
    SENEGAL_CFA_FRANC("Senegal-Cfa Franc"),
    SERBIA_DINAR("Serbia-Dinar"),
    SERBIA_EURO_DINAR("Serbia-Euro Dinar"),
    SEYCHELLES_RUPEE("Seychelles-Rupee"),
    SIERRA_LEONE_LEONE("Sierra Leone-Leone"),
    SIERRA_LEONE_OLD_LEONE("Sierra Leone-Old Leone"),
    SINGAPORE_DOLLAR("Singapore-Dollar"),
    SLOVAK_REPUBLIC_EURO("Slovak Republic-Euro"),
    SLOVAK_KORUN("Slovak-Korun"),
    SLOVAKIA_EURO("Slovakia-Euro"),
    SLOVENIA_EURO("Slovenia-Euro"),
    SLOVENIA_TOLARS("Slovenia-Tolars"),
    SOLOMON_ISLANDS_DOLLAR("Solomon Islands-Dollar"),
    SOMALI_SHILLING("Somali-Shilling"),
    SOUTH_AFRICA_RAND("South Africa-Rand"),
    SOUTH_SUDAN_SUDANESE_POUND("South Sudan-Sudanese Pound"),
    SPAIN_EURO("Spain-Euro"),
    SPAIN_PESETA("Spain-Peseta"),
    SRI_LANKA_RUPEE("Sri Lanka-Rupee"),
    ST_LUCIA_EAST_CARIBBEAN_DOLLAR("St. Lucia-East Caribbean Dollar"),
    SUDAN_DINAR("Sudan-Dinar"),
    SUDAN_POUND("Sudan-Pound"),
    SUDAN_SUDANESE_POUND("Sudan-Sudanese Pound"),
    SURINAME_DOLLAR("Suriname-Dollar"),
    SURINAME_GUILDER("Suriname-Guilder"),
    SWAZILAND_LILANGENI("Swaziland-Lilangeni"),
    SWEDEN_KRONA("Sweden-Krona"),
    SWITZERLAND_FRANC("Switzerland-Franc"),
    SYRIA_POUND("Syria-Pound"),
    TAIWAN_DOLLAR("Taiwan-Dollar"),
    TAJIKISTAN_SOMONI("Tajikistan-Somoni"),
    TANZANIA_SHILLING("Tanzania-Shilling"),
    THAILAND_BAHT("Thailand-Baht"),
    TIMOR_LESTE_DILI_ALTERNATE("Timor-Leste Dili"),
    TIMOR_LESTE_DILI("Timor-Leste-Dili"),
    TOGO_CFA_FRANC("Togo-Cfa Franc"),
    TONGA_PA_ANGA("Tonga-Pa'Anga"),
    TRINIDAD_TOBAGO_DOLLAR("Trinidad & Tobago-Dollar"),
    TUNISIA_DINAR("Tunisia-Dinar"),
    TURKEY_LIRA("Turkey-Lira"),
    TURKEY_NEW_LIRA("Turkey-New Lira"),
    TURKMENISTAN_MANAT("Turkmenistan-Manat"),
    TURKMENISTAN_NEW_MANAT("Turkmenistan-New Manat"),
    UGANDA_SHILLING("Uganda-Shilling"),
    UKRAINE_HRYVNIA("Ukraine-Hryvnia"),
    UNITED_ARAB_EMIRATES_DIRHAM("United Arab Emirates-Dirham"),
    UNITED_KINGDOM_POUND("United Kingdom-Pound"),
    UNITED_KINGDOM_POUND_STERLING("United Kingdom-Pound Sterling"),
    URUGUAY_PESO("Uruguay-Peso"),
    UZBEKISTAN_SOM("Uzbekistan-Som"),
    VANUATU_VATU("Vanuatu-Vatu"),
    VENEZUELA_BOLIVAR("Venezuela-Bolivar"),
    VENEZUELA_BOLIVAR_FUERTE("Venezuela-Bolivar Fuerte"),
    VENEZUELA_BOLIVAR_SOBERANO("Venezuela-Bolivar Soberano"),
    VENEZUELA_FUERTE("Venezuela-Fuerte"),
    VENEZUELA_SOBERANO("Venezuela-Soberano"),
    VIETNAM_DONG("Vietnam-Dong"),
    WESTERN_SAMOA_TALA("Western Samoa-Tala"),
    YEMEN_RIAL("Yemen-Rial"),
    ZAMBIA_KWACHA("Zambia-Kwacha"),
    ZAMBIA_NEW_KWACHA("Zambia-New Kwacha"),
    ZIMBABWE_DOLLAR("Zimbabwe-Dollar"),
    ZIMBABWE_GOLD("Zimbabwe-Gold"),
    ZIMBABWE_RTGS("Zimbabwe-Rtgs");

    private static final Map<String, Currency> BY_TREASURY_NAME = Arrays.stream(values())
            .collect(Collectors.toUnmodifiableMap(Currency::getTreasuryName, Function.identity()));

    private final String treasuryName;

    @JsonValue
    public String getTreasuryName() {
        return treasuryName;
    }

    @JsonCreator
    public static Currency fromTreasuryName(String name) {
        return Optional.ofNullable(name)
                .map(BY_TREASURY_NAME::get)
                .orElseThrow(() -> new IllegalArgumentException(
                        "Unsupported currency. Use a Treasury country-currency name, such as Canada-Dollar"
                ));
    }
}
